apiVersion: v1
kind: Service
metadata:
  name: ngx-instance-1
  labels:
    name: ngx-instance-1
  annotations:
    external-dns.alpha.kubernetes.io/hostname: bdb.sandbox.bloomware.services
    external-dns.alpha.kubernetes.io/ttl: "30"
spec:
  selector:
    app: ngx-instance-0-dep
  ports:
  - port: 443
    targetPort: 443
    name: public-secure-node-port
    protocol: TCP
  - port: 27017
    targetPort: 27017
    name: public-mdb-port
    protocol: TCP
  - port: 9986
    targetPort: 9986
    name: tm-pub-key-access
    protocol: TCP
  - port: 26656
    targetPort: 26656
    protocol: TCP
    name: tm-p2p-port
  - port: 80
    targetPort: 80
    name: public-insecure-node-port
    protocol: TCP
  type: LoadBalancer
